export const mockData = {
  data: [
    {
      id: 1,
      name: "Pubg",
      region: "US",
      createdOn: 1647856749371,
      price: "Price info of Pubg",
      monthlyPrice: 100,
      halfYearlyPrice: 500,
      yearlyPrice: 900,
      popUpIcon: "pubg",
      csv: "Some CSV link for Pubg",
      report: "Some report link for Pubg",
      image_url: "Some image url of the campaign",
    },
    {
      id: 2,
      name: "Super Jewels Quest",
      region: "CA, FR",
      createdOn: 1689856949371,
      price: "Price info of Super Jewels Quest",
      monthlyPrice: 150,
      halfYearlyPrice: 600,
      yearlyPrice: 800,
      popUpIcon: "superjewels",
      csv: "Some CSV link for Super Jewels Quest",
      report: "Some report link for Super Jewels Ques",
      image_url: "Some image url of the campaign",
    },
    {
      id: 3,
      name: "Mole Slayer",
      region: "FR",
      createdOn: 1647856749371,
      price: "Price info of Mole Slayer",
      monthlyPrice: 200,
      halfYearlyPrice: 700,
      yearlyPrice: 900,
      popUpIcon: "moleslayer",
      csv: "Some CSV link for Mole Slayer",
      report: "Some report link for Mole Slayer",
      image_url: "Some image url of the campaign",
    },
    {
      id: 4,
      name: "Mancala Mix",
      region: "JP",
      createdOn: 1647856749371,
      price: "Price info of Mancala Mix",
      monthlyPrice: 100,
      halfYearlyPrice: 500,
      yearlyPrice: 900,
      popUpIcon: "mancalamix",
      csv: "Some CSV link for Mancala Mix",
      report: "Some report link for Mancala Mix",
      image_url: "Some image url of the campaign",
    },
  ],
};
